// Curated /guides/ hub categories.
// To move a guide, move its slug between the arrays below.
// Slugs map to src/guides/<slug>.njk. The index page reads title/description from each guide file.

module.exports = [
  {
    title: "Start Here",
    description: "The shortest path into frost-aware, heat-aware garden planning.",
    slugs: [
      "how-to-plan-a-garden-in-a-short-growing-season",
      "how-frost-dates-and-growing-degree-days-work-together",
      "why-days-to-maturity-isnt-enough-in-cold-climates",
      "will-my-crop-mature-before-first-frost",
      "what-crops-grow-in-short-growing-seasons",
    ],
  },
  {
    title: "Frost Dates & Freeze Risk",
    description: "Last frost, first frost, frost probability, freeze severity, and local microclimates.",
    slugs: [
      "32f-vs-28f-what-temperature-kills-plants",
      "average-frost-date-vs-actual-weather",
      "can-i-plant-tomatoes-after-the-last-frost-date",
      "how-microclimates-change-frost-dates",
      "how-to-find-your-first-frost-date",
      "how-to-find-your-last-frost-date",
      "how-to-use-your-frost-dates-to-plan-your-garden",
      "light-freeze-vs-hard-freeze",
      "should-you-wait-2-weeks-after-frost-to-plant",
      "what-does-50-percent-frost-probability-mean",
      "what-is-a-killing-frost",
      "why-frost-dates-matter-more-than-planting-calendars",
      "why-your-backyard-may-be-warmer-or-colder-than-your-zip-code",
      "why-your-last-frost-date-isnt-exact",
    ],
  },
  {
    title: "Growing Degree Days & Crop Maturity",
    description: "Guides for judging whether a crop has enough time and heat to finish.",
    slugs: [
      "can-sweet-corn-mature-before-first-frost",
      "crops-that-mature-in-under-90-frost-free-days",
      "crops-that-need-fewer-than-1000-growing-degree-days",
      "do-you-have-enough-growing-degree-days-for-winter-squash",
      "how-elevation-affects-growing-degree-days",
      "how-many-frost-free-days-do-potatoes-need",
      "how-many-growing-degree-days-do-tomatoes-need",
      "what-crops-fail-in-short-growing-seasons-and-why",
      "what-is-considered-a-short-growing-season",
      "when-is-it-too-late-to-plant-for-fall-harvest",
      "will-peppers-mature-before-first-frost-in-a-short-growing-season",
    ],
  },
  {
    title: "Seed Starting & Transplanting",
    description: "Indoor starts, hardening off, transplant timing, grow lights, trays, and seedling problems.",
    slugs: [
      "72-cell-vs-128-cell-seed-trays",
      "best-bottom-watering-trays-for-seedlings",
      "best-containers-for-starting-seeds-indoors",
      "best-fan-for-seedlings-indoors",
      "best-fan-setup-for-seed-starting-shelves",
      "best-grow-lights-for-seedlings",
      "best-heat-mat-for-seedlings",
      "best-humidity-dome-for-seed-starting",
      "best-labels-for-seed-starting-that-dont-fade",
      "best-mini-greenhouse-for-hardening-off-seedlings",
      "best-mini-greenhouse-for-starting-seedlings-outdoors",
      "best-newspaper-pot-maker-for-seedlings",
      "best-ollas-for-tomatoes-in-containers",
      "best-paper-pot-maker-for-seed-starting",
      "best-potting-up-pots-for-seedlings",
      "best-seed-dibber-for-seed-starting-trays",
      "best-setup-for-hardening-off-seedlings-outdoors",
      "best-setup-for-starting-seeds-in-a-basement",
      "best-shelving-setup-for-starting-seeds-indoors",
      "best-soil-blocker-for-seed-starting",
      "best-seed-starting-mix",
      "best-timer-for-grow-lights-for-seedlings",
      "best-watering-method-for-seedlings-indoors",
      "best-way-to-harden-off-seedlings-in-windy-areas",
      "best-way-to-reuse-seed-starting-soil",
      "best-widger-and-dibber-set-for-seedlings",
      "can-seedlings-survive-35-degrees",
      "can-seedlings-survive-40-degrees",
      "can-you-start-seeds-without-grow-lights",
      "chaos-gardening-short-growing-season",
      "cold-frame-vs-mini-greenhouse-for-seedlings",
      "cold-tolerance-of-seedlings",
      "counting-backward-from-frost-how-seed-timing-works",
      "do-you-need-a-fan-for-seedlings",
      "do-you-need-a-humidity-dome-for-seed-starting",
      "how-far-should-grow-lights-be-from-seedlings",
      "how-long-should-grow-lights-be-on-for-seedlings",
      "how-much-light-do-seedlings-need",
      "how-to-harden-off-seedlings",
      "how-to-keep-seedlings-from-drying-out-during-the-day",
      "how-to-prevent-damping-off-in-seedlings",
      "how-to-start-seeds-in-a-cold-house",
      "mini-soil-blocker-vs-2-inch-blocker-for-peppers",
      "paper-pot-maker-vs-soil-blocker",
      "seed-dibber-vs-pencil-for-planting-seeds",
      "seed-starting-in-a-short-growing-season",
      "seed-starting-schedule-zone-3-to-5",
      "seed-starting-supplies-checklist",
      "shop-lights-vs-grow-lights",
      "starting-seeds-too-early",
      "what-happens-to-seedlings-at-32-degrees",
      "what-is-seed-starting-mix",
      "what-temperature-is-too-cold-for-hardened-off-seedlings",
      "best-timer-for-grow-lights-mechanical-vs-digital",
      "when-a-heat-mat-helps-for-seed-starting",
      "when-a-thermostat-matters-for-seed-starting-heat-mats",
      "when-should-you-fertilize-seedlings",
      "when-to-pot-up-seedlings",
      "when-to-start-seeds-indoors",
      "when-to-transplant-seedlings-outdoors",
      "why-seedlings-get-leggy",
    ],
  },
  {
    title: "Season Extension & Plant Protection",
    description: "Row cover, frost cloth, cold frames, low tunnels, greenhouse repairs, shade cloth, and plant protection setups.",
    slugs: [
      "best-beneficial-nematodes-for-fungus-gnats",
      "best-clips-and-hoops-for-securing-frost-cloth",
      "best-clips-for-holding-shade-cloth-in-wind",
      "best-cold-frame-for-raised-beds",
      "best-frost-blanket-for-tomatoes",
      "best-frost-cloth-for-vegetable-gardens-by-temperature-rating",
      "best-greenhouse-repair-tape-for-torn-plastic",
      "best-greenhouse-tomato-support-system-for-home-gardeners",
      "best-insect-netting-for-brassicas",
      "best-insect-netting-height-for-raised-bed-tunnels",
      "best-low-tunnel-kit-for-home-vegetable-gardens",
      "best-low-tunnel-setup-for-wind-protection-vs-insect-control",
      "best-mini-greenhouse-shelf-for-balcony-gardens",
      "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
      "best-place-to-buy-season-extension-supplies-for-home-gardeners",
      "best-repair-kit-for-mini-greenhouse-covers",
      "best-row-cover-for-early-spring-brassicas",
      "best-row-cover-hoops-for-raised-beds",
      "best-setup-for-extending-pepper-harvest-into-fall",
      "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
      "best-shade-cloth-setup-for-west-facing-gardens",
      "best-way-to-secure-row-cover-in-high-wind",
      "best-zipper-door-kit-for-diy-greenhouse-plastic",
      "cold-frame-vs-low-tunnel",
      "climate-resilient-vegetable-gardening-short-seasons",
      "floating-row-cover-vs-frost-blanket",
      "greenhouse-patch-tape-vs-clear-tarp-tape",
      "how-many-degrees-does-frost-cloth-protect",
      "how-to-add-2-to-4-weeks-to-your-growing-season",
      "insect-netting-vs-row-cover-for-brassicas",
      "metal-vs-fiberglass-garden-hoops-for-row-cover",
      "pop-up-plant-protector-vs-insect-net-tunnel",
      "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
    ],
  },
  {
    title: "Crop-Specific Timing Questions",
    description: "Crop-level timing problems such as late planting, cold limits, and short-season maturity risk.",
    slugs: [
      "best-reusable-vine-clips-for-peppers-and-eggplant",
      "best-seed-starting-kit-for-tomatoes-and-peppers",
      "best-seed-starting-trays",
      "can-tomato-seedlings-survive-a-light-frost",
      "how-cold-is-too-cold-for-pepper-seedlings",
      "how-cold-is-too-cold-for-tomato-seedlings",
      "is-45-degrees-too-cold-for-tomato-plants",
      "is-it-too-late-to-plant-beans",
      "is-it-too-late-to-plant-cucumbers",
      "is-it-too-late-to-plant-peppers",
      "is-it-too-late-to-plant-pumpkins",
      "is-it-too-late-to-plant-tomatoes",
      "too-late-to-plant-peppers",
      "too-late-to-start-peppers-in-zone-4",
      "too-late-to-start-tomatoes-in-zone-4",
      "too-late-to-start-tomatoes-in-zone-5",
      "what-temperature-is-safe-to-transplant-peppers",
      "when-to-start-tomatoes-in-zone-3",
      "will-tomatoes-grow-in-a-100-day-growing-season",
    ],
  },
  {
    title: "Seeds, Varieties & Garden Gifts",
    description: "Seed companies, fast-maturing varieties, succession seeds, seed storage, seed saving, and practical garden gifts.",
    slugs: [
      "best-garden-planner-gift-certificate",
      "best-garden-planner-subscription-gift-for-gardeners",
      "best-gardening-software-gift-for-beginners",
      "best-gift-for-a-vegetable-gardener-who-has-everything",
      "best-gift-for-someone-starting-a-vegetable-garden",
      "best-gift-seed-collection-for-gardeners",
      "best-pollination-bags-for-pepper-seed-saving",
      "best-pollination-bags-for-saving-tomato-or-pepper-seed",
      "best-retailer-for-fast-maturing-vegetable-varieties",
      "best-seed-collection-for-beginner-vegetable-gardeners",
      "best-seed-company-for-container-vegetables-in-cool-climates",
      "best-seed-company-for-cool-climate-vegetables",
      "best-seed-company-for-fast-maturing-varieties",
      "best-seed-company-for-short-season-gardens",
      "best-seed-company-for-succession-planting",
      "best-seed-company-gift-card-for-gardeners",
      "best-seed-organizer-binder-for-gardeners",
      "best-seed-saving-envelopes-for-home-gardeners",
      "best-seed-storage-box-for-vegetable-seeds",
      "best-source-for-succession-planting-seed-mixes",
      "best-vegetable-seed-gift-box-for-gardeners",
      "pollination-bags-vs-organza-bags-for-seed-saving",
    ],
  },
  {
    title: "Supports, Grafting & Vertical Growing",
    description: "Grafting clips, tomato hooks, vine clips, trellis connectors, slings, and vertical growing supports.",
    slugs: [
      "best-tomato-cages",
      "best-cucumber-clips-for-vertical-growing",
      "best-hanging-line-clips-for-vine-crops",
      "best-trellis-connectors-for-cucumber-teepees",
      "best-watermelon-support-net-for-vertical-growing",
      "cucumber-clips-vs-tomato-clips",
      "diy-cucumber-trellis-connectors-vs-zip-ties",
      "fruit-sling-vs-net-bag-for-trellised-melons",
      "tomato-hooks-vs-clips-for-vertical-growing",
    ],
  },
  {
    title: "Watering, Sensors & Pest Protection",
    description: "Watering systems, moisture sensors, slug/snail barriers, insect netting, and crop protection tools.",
    slugs: [
      "best-copper-tape-for-slugs-in-raised-beds",
      "best-garden-sensor-for-vacation-watering-checks",
      "best-olla-system-for-vacation-watering-outdoors",
      "best-sensor-for-monitoring-garden-beds-remotely",
      "best-snail-barrier-for-patio-planters",
      "best-terracotta-watering-pots-for-vacation-watering",
      "best-zigbee-soil-moisture-sensor-for-outdoor-plants",
      "copper-tape-vs-copper-mesh-for-snails",
      "drip-irrigation-vs-olla-pots-for-tomatoes",
      "smart-soil-sensor-vs-manual-moisture-meter-for-gardens",
    ],
  },
  {
    title: "Garden Planning Tools & Software",
    description: "Garden planner subscriptions, software, and planning gift ideas.",
    slugs: [
      "is-a-garden-planner-subscription-worth-it",
      "is-growveg-worth-it-for-home-gardeners",
      "ai-garden-planning-guide",
      "ai-garden-planner-prompts",
      "can-chatgpt-make-a-planting-calendar",
      "use-ai-to-choose-what-to-grow-short-season",
      "ai-raised-bed-garden-planner",
    ],
  },
  {
    title: "Planting Tools, Storage & Garden Gear",
    description: "Small practical tools that do not fit neatly into the planning, seed-starting, or protection groups.",
    slugs: [
      "best-hand-seeder-for-carrots-and-lettuce",
      "best-mini-seed-spreader-for-tiny-seeds",
      "best-products-to-ripen-tomatoes-before-frost",
      "best-soil-thermometer",
      "binder-vs-box-for-storing-seed-packets",
      "soil-thermometer-vs-infrared-thermometer-for-planting-decisions",
    ],
  },
];
