// Curated related-guide blocks for individual guide articles.
// Keys are guide slugs from src/guides/<slug>.njk.
// Each page gets four intentional links: usually one parent concept, two close sibling articles, and one next-step guide.
// Keep this file curated by editing the arrays directly rather than relying on popularity or automatic fallbacks.

module.exports = {

  // Start Here
  "how-to-plan-a-garden-in-a-short-growing-season": [
    "how-to-find-your-last-frost-date",
    "how-to-find-your-first-frost-date",
    "what-does-50-percent-frost-probability-mean",
    "average-frost-date-vs-actual-weather",
  ],
  "how-frost-dates-and-growing-degree-days-work-together": [
    "will-my-crop-mature-before-first-frost",
    "why-days-to-maturity-isnt-enough-in-cold-climates",
    "crops-that-need-fewer-than-1000-growing-degree-days",
    "crops-that-mature-in-under-90-frost-free-days",
  ],
  "why-days-to-maturity-isnt-enough-in-cold-climates": [
    "how-frost-dates-and-growing-degree-days-work-together",
    "will-my-crop-mature-before-first-frost",
    "what-crops-fail-in-short-growing-seasons-and-why",
    "best-seed-company-for-fast-maturing-varieties",
  ],
  "will-my-crop-mature-before-first-frost": [
    "how-frost-dates-and-growing-degree-days-work-together",
    "crops-that-mature-in-under-90-frost-free-days",
    "do-you-have-enough-growing-degree-days-for-winter-squash",
    "can-sweet-corn-mature-before-first-frost",
  ],
  "what-crops-grow-in-short-growing-seasons": [
    "how-frost-dates-and-growing-degree-days-work-together",
    "will-my-crop-mature-before-first-frost",
    "why-days-to-maturity-isnt-enough-in-cold-climates",
    "crops-that-need-fewer-than-1000-growing-degree-days",
  ],

  // Frost Dates & Freeze Risk
  "32f-vs-28f-what-temperature-kills-plants": [
    "light-freeze-vs-hard-freeze",
    "what-is-a-killing-frost",
  ],
  "average-frost-date-vs-actual-weather": [
    "how-to-find-your-last-frost-date",
    "how-to-find-your-first-frost-date",
    "what-does-50-percent-frost-probability-mean",
    "why-your-last-frost-date-isnt-exact",
  ],
  "can-i-plant-tomatoes-after-the-last-frost-date": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "how-microclimates-change-frost-dates": [
    "why-your-backyard-may-be-warmer-or-colder-than-your-zip-code",
    "best-soil-thermometer",
    "how-to-find-your-last-frost-date",
  ],
  "how-to-find-your-first-frost-date": [
    "how-to-find-your-last-frost-date",
    "what-does-50-percent-frost-probability-mean",
    "average-frost-date-vs-actual-weather",
    "why-your-last-frost-date-isnt-exact",
  ],
  "how-to-find-your-last-frost-date": [
    "how-to-find-your-first-frost-date",
    "what-does-50-percent-frost-probability-mean",
    "average-frost-date-vs-actual-weather",
    "why-your-last-frost-date-isnt-exact",
  ],
  "how-to-use-your-frost-dates-to-plan-your-garden": [
    "how-to-find-your-last-frost-date",
    "how-to-find-your-first-frost-date",
    "what-does-50-percent-frost-probability-mean",
    "average-frost-date-vs-actual-weather",
  ],
  "light-freeze-vs-hard-freeze": [
    "32f-vs-28f-what-temperature-kills-plants",
    "what-is-a-killing-frost",
  ],
  "should-you-wait-2-weeks-after-frost-to-plant": [
    "how-to-find-your-last-frost-date",
    "how-to-find-your-first-frost-date",
    "what-does-50-percent-frost-probability-mean",
    "average-frost-date-vs-actual-weather",
  ],
  "what-does-50-percent-frost-probability-mean": [
    "average-frost-date-vs-actual-weather",
    "why-your-last-frost-date-isnt-exact",
    "how-to-find-your-last-frost-date",
  ],
  "what-is-a-killing-frost": [
    "32f-vs-28f-what-temperature-kills-plants",
    "light-freeze-vs-hard-freeze",
  ],
  "why-frost-dates-matter-more-than-planting-calendars": [
    "how-to-find-your-last-frost-date",
    "how-to-find-your-first-frost-date",
    "what-does-50-percent-frost-probability-mean",
    "average-frost-date-vs-actual-weather",
  ],
  "why-your-backyard-may-be-warmer-or-colder-than-your-zip-code": [
    "how-microclimates-change-frost-dates",
    "best-soil-thermometer",
    "how-to-find-your-last-frost-date",
  ],
  "why-your-last-frost-date-isnt-exact": [
    "how-to-find-your-last-frost-date",
    "how-to-find-your-first-frost-date",
    "what-does-50-percent-frost-probability-mean",
    "average-frost-date-vs-actual-weather",
  ],

  // Growing Degree Days & Crop Maturity
  "can-sweet-corn-mature-before-first-frost": [
    "how-many-growing-degree-days-do-tomatoes-need",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "do-you-have-enough-growing-degree-days-for-winter-squash",
  ],
  "crops-that-mature-in-under-90-frost-free-days": [
    "how-frost-dates-and-growing-degree-days-work-together",
    "will-my-crop-mature-before-first-frost",
    "why-days-to-maturity-isnt-enough-in-cold-climates",
    "crops-that-need-fewer-than-1000-growing-degree-days",
  ],
  "crops-that-need-fewer-than-1000-growing-degree-days": [
    "how-frost-dates-and-growing-degree-days-work-together",
    "will-my-crop-mature-before-first-frost",
    "why-days-to-maturity-isnt-enough-in-cold-climates",
    "crops-that-mature-in-under-90-frost-free-days",
  ],
  "do-you-have-enough-growing-degree-days-for-winter-squash": [
    "how-many-growing-degree-days-do-tomatoes-need",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "can-sweet-corn-mature-before-first-frost",
  ],
  "how-elevation-affects-growing-degree-days": [
    "how-microclimates-change-frost-dates",
    "why-your-backyard-may-be-warmer-or-colder-than-your-zip-code",
    "best-soil-thermometer",
  ],
  "how-many-frost-free-days-do-potatoes-need": [
    "how-many-growing-degree-days-do-tomatoes-need",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "do-you-have-enough-growing-degree-days-for-winter-squash",
  ],
  "how-many-growing-degree-days-do-tomatoes-need": [
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "do-you-have-enough-growing-degree-days-for-winter-squash",
    "can-sweet-corn-mature-before-first-frost",
  ],
  "what-crops-fail-in-short-growing-seasons-and-why": [
    "how-frost-dates-and-growing-degree-days-work-together",
    "will-my-crop-mature-before-first-frost",
    "why-days-to-maturity-isnt-enough-in-cold-climates",
    "crops-that-need-fewer-than-1000-growing-degree-days",
  ],
  "what-is-considered-a-short-growing-season": [
    "how-frost-dates-and-growing-degree-days-work-together",
    "will-my-crop-mature-before-first-frost",
    "why-days-to-maturity-isnt-enough-in-cold-climates",
    "crops-that-need-fewer-than-1000-growing-degree-days",
  ],
  "when-is-it-too-late-to-plant-for-fall-harvest": [
    "is-it-too-late-to-plant-beans",
    "is-it-too-late-to-plant-cucumbers",
    "is-it-too-late-to-plant-pumpkins",
    "is-it-too-late-to-plant-tomatoes",
  ],
  "will-peppers-mature-before-first-frost-in-a-short-season": [
    "how-many-growing-degree-days-do-tomatoes-need",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "do-you-have-enough-growing-degree-days-for-winter-squash",
    "can-sweet-corn-mature-before-first-frost",
  ],

  // Seed Starting & Transplanting
  "72-cell-vs-128-cell-seed-trays": [
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
    "best-soil-blocker-for-seed-starting",
  ],
  "best-bottom-watering-trays-for-seedlings": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "best-containers-for-starting-seeds-indoors": [
    "72-cell-vs-128-cell-seed-trays",
    "best-potting-up-pots-for-seedlings",
    "best-soil-blocker-for-seed-starting",
  ],
  "best-fan-for-seedlings-indoors": [
    "how-to-prevent-damping-off-in-seedlings",
    "do-you-need-a-fan-for-seedlings",
    "best-watering-method-for-seedlings-indoors",
    "how-to-keep-seedlings-from-drying-out-during-the-day",
  ],
  "best-fan-setup-for-seed-starting-shelves": [
    "how-to-prevent-damping-off-in-seedlings",
    "do-you-need-a-fan-for-seedlings",
    "best-fan-for-seedlings-indoors",
    "best-watering-method-for-seedlings-indoors",
  ],
  "best-grow-lights-for-seedlings": [
    "shop-lights-vs-grow-lights",
    "how-far-should-grow-lights-be-from-seedlings",
    "how-long-should-grow-lights-be-on-for-seedlings",
    "can-you-start-seeds-without-grow-lights",
  ],
  "best-heat-mat-for-seedlings": [
    "do-you-need-a-heat-mat-to-start-seeds",
    "when-a-thermostat-matters-for-seed-starting-heat-mats",
    "how-to-start-seeds-in-a-cold-house",
  ],
  "best-humidity-dome-for-seed-starting": [
    "seed-starting-supplies-checklist",
    "best-setup-for-starting-seeds-in-a-basement",
    "best-shelving-setup-for-starting-seeds-indoors",
    "best-seed-starting-mix",
  ],
  "best-labels-for-seed-starting-that-dont-fade": [
    "seed-starting-supplies-checklist",
    "best-setup-for-starting-seeds-in-a-basement",
    "best-shelving-setup-for-starting-seeds-indoors",
    "best-seed-starting-mix",
  ],
  "best-mini-greenhouse-for-hardening-off-seedlings": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
    "cold-tolerance-of-seedlings",
  ],
  "best-mini-greenhouse-for-starting-seedlings-outdoors": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
  ],
  "best-newspaper-pot-maker-for-seedlings": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "best-ollas-for-tomatoes-in-containers": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "best-paper-pot-maker-for-seed-starting": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "best-potting-up-pots-for-seedlings": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-soil-blocker-for-seed-starting",
  ],
  "best-seed-dibber-for-seed-starting-trays": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "best-setup-for-hardening-off-seedlings-outdoors": [
    "how-to-harden-off-seedlings",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
    "cold-tolerance-of-seedlings",
  ],
  "best-setup-for-starting-seeds-in-a-basement": [
    "seed-starting-supplies-checklist",
    "best-shelving-setup-for-starting-seeds-indoors",
    "best-seed-starting-mix",
    "what-is-seed-starting-mix",
  ],
  "best-shelving-setup-for-starting-seeds-indoors": [
    "seed-starting-supplies-checklist",
    "best-setup-for-starting-seeds-in-a-basement",
    "best-seed-starting-mix",
    "what-is-seed-starting-mix",
  ],
  "best-soil-blocker-for-seed-starting": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "best-seed-starting-mix": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "best-timer-for-grow-lights-for-seedlings": [
    "best-grow-lights-for-seedlings",
    "shop-lights-vs-grow-lights",
    "how-far-should-grow-lights-be-from-seedlings",
    "how-long-should-grow-lights-be-on-for-seedlings",
  ],
  "best-watering-method-for-seedlings-indoors": [
    "how-to-prevent-damping-off-in-seedlings",
    "do-you-need-a-fan-for-seedlings",
    "best-fan-for-seedlings-indoors",
    "how-to-keep-seedlings-from-drying-out-during-the-day",
  ],
  "best-way-to-harden-off-seedlings-in-windy-areas": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
  ],
  "best-way-to-reuse-seed-starting-soil": [
    "seed-starting-short-season",
    "when-to-start-seeds-indoors",
    "counting-backward-from-frost-how-seed-timing-works",
    "starting-seeds-too-early",
  ],
  "best-widger-and-dibber-set-for-seedlings": [
    "seed-starting-supplies-checklist",
    "best-setup-for-starting-seeds-in-a-basement",
    "best-shelving-setup-for-starting-seeds-indoors",
    "best-seed-starting-mix",
  ],
  "can-seedlings-survive-35-degrees": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
  ],
  "can-seedlings-survive-40-degrees": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
  ],
  "can-you-start-seeds-without-grow-lights": [
    "best-grow-lights-for-seedlings",
    "shop-lights-vs-grow-lights",
    "how-far-should-grow-lights-be-from-seedlings",
    "how-long-should-grow-lights-be-on-for-seedlings",
  ],
  "cold-frame-vs-mini-greenhouse-for-seedlings": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-tolerance-of-seedlings",
  ],
  "cold-tolerance-of-seedlings": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
  ],
  "counting-backward-from-frost-how-seed-timing-works": [
    "seed-starting-short-season",
    "when-to-start-seeds-indoors",
    "starting-seeds-too-early",
    "when-to-transplant-seedlings-outdoors",
  ],
  "do-you-need-a-fan-for-seedlings": [
    "how-to-prevent-damping-off-in-seedlings",
    "best-fan-for-seedlings-indoors",
    "best-watering-method-for-seedlings-indoors",
    "how-to-keep-seedlings-from-drying-out-during-the-day",
  ],
  "do-you-need-a-humidity-dome-for-seed-starting": [
    "seed-starting-supplies-checklist",
    "best-setup-for-starting-seeds-in-a-basement",
    "best-shelving-setup-for-starting-seeds-indoors",
    "best-seed-starting-mix",
  ],
  "how-far-should-grow-lights-be-from-seedlings": [
    "best-grow-lights-for-seedlings",
    "shop-lights-vs-grow-lights",
    "how-long-should-grow-lights-be-on-for-seedlings",
    "can-you-start-seeds-without-grow-lights",
  ],
  "how-long-should-grow-lights-be-on-for-seedlings": [
    "best-grow-lights-for-seedlings",
    "shop-lights-vs-grow-lights",
    "how-far-should-grow-lights-be-from-seedlings",
    "can-you-start-seeds-without-grow-lights",
  ],
  "how-much-light-do-seedlings-need": [
    "best-grow-lights-for-seedlings",
    "shop-lights-vs-grow-lights",
    "how-far-should-grow-lights-be-from-seedlings",
    "how-long-should-grow-lights-be-on-for-seedlings",
  ],
  "how-to-harden-off-seedlings": [
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
    "cold-tolerance-of-seedlings",
  ],
  "how-to-keep-seedlings-from-drying-out-during-the-day": [
    "how-to-prevent-damping-off-in-seedlings",
    "do-you-need-a-fan-for-seedlings",
    "best-fan-for-seedlings-indoors",
    "best-watering-method-for-seedlings-indoors",
  ],
  "how-to-prevent-damping-off-in-seedlings": [
    "do-you-need-a-fan-for-seedlings",
    "best-fan-for-seedlings-indoors",
    "best-watering-method-for-seedlings-indoors",
    "how-to-keep-seedlings-from-drying-out-during-the-day",
  ],
  "how-to-start-seeds-in-a-cold-house": [
    "do-you-need-a-heat-mat-to-start-seeds",
    "best-heat-mat-for-seedlings",
    "when-a-thermostat-matters-for-seed-starting-heat-mats",
  ],
  "mini-soil-blocker-vs-2-inch-blocker-for-peppers": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "paper-pot-maker-vs-soil-blocker": [
    "72-cell-vs-128-cell-seed-trays",
    "best-containers-for-starting-seeds-indoors",
    "best-potting-up-pots-for-seedlings",
  ],
  "seed-dibber-vs-pencil-for-planting-seeds": [
    "seed-starting-supplies-checklist",
    "best-setup-for-starting-seeds-in-a-basement",
    "best-shelving-setup-for-starting-seeds-indoors",
    "best-seed-starting-mix",
  ],
  "seed-starting-short-season": [
    "when-to-start-seeds-indoors",
    "seed-starting-schedule-zone-3-to-5",
    "starting-seeds-too-early",
    "can-you-start-seeds-without-grow-lights",
  ],
  "seed-starting-schedule-zone-3-to-5": [
    "seed-starting-short-season",
    "when-to-start-seeds-indoors",
    "counting-backward-from-frost-how-seed-timing-works",
    "starting-seeds-too-early",
  ],
  "seed-starting-supplies-checklist": [
    "best-setup-for-starting-seeds-in-a-basement",
    "best-shelving-setup-for-starting-seeds-indoors",
    "best-seed-starting-mix",
    "what-is-seed-starting-mix",
  ],
  "shop-lights-vs-grow-lights": [
    "best-grow-lights-for-seedlings",
    "how-far-should-grow-lights-be-from-seedlings",
    "how-long-should-grow-lights-be-on-for-seedlings",
    "can-you-start-seeds-without-grow-lights",
  ],
  "starting-seeds-too-early": [
    "seed-starting-short-season",
    "when-to-start-seeds-indoors",
    "counting-backward-from-frost-how-seed-timing-works",
    "when-to-transplant-seedlings-outdoors",
  ],
  "what-happens-to-seedlings-at-32-degrees": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
  ],
  "what-is-seed-starting-mix": [
    "seed-starting-supplies-checklist",
    "best-setup-for-starting-seeds-in-a-basement",
    "best-shelving-setup-for-starting-seeds-indoors",
    "best-seed-starting-mix",
  ],
  "what-temperature-is-too-cold-for-hardened-off-seedlings": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
  ],
  "best-timer-for-grow-lights-mechanical-vs-digital": [
    "best-grow-lights-for-seedlings",
    "shop-lights-vs-grow-lights",
    "how-far-should-grow-lights-be-from-seedlings",
    "how-long-should-grow-lights-be-on-for-seedlings",
  ],
  "do-you-need-a-heat-mat-to-start-seeds": [
    "best-heat-mat-for-seedlings",
    "when-a-thermostat-matters-for-seed-starting-heat-mats",
    "how-to-start-seeds-in-a-cold-house",
  ],
  "when-a-thermostat-matters-for-seed-starting-heat-mats": [
    "do-you-need-a-heat-mat-to-start-seeds",
    "best-heat-mat-for-seedlings",
    "how-to-start-seeds-in-a-cold-house",
  ],
  "when-should-you-fertilize-seedlings": [
    "how-to-prevent-damping-off-in-seedlings",
    "do-you-need-a-fan-for-seedlings",
    "best-fan-for-seedlings-indoors",
    "best-watering-method-for-seedlings-indoors",
  ],
  "when-to-pot-up-seedlings": [
    "seed-starting-short-season",
    "when-to-start-seeds-indoors",
    "counting-backward-from-frost-how-seed-timing-works",
    "starting-seeds-too-early",
  ],
  "when-to-start-seeds-indoors": [
    "counting-backward-from-frost-how-seed-timing-works",
    "starting-seeds-too-early",
    "when-to-pot-up-seedlings",
    "when-to-transplant-seedlings-outdoors",
  ],
  "when-to-transplant-seedlings-outdoors": [
    "how-to-harden-off-seedlings",
    "best-setup-for-hardening-off-seedlings-outdoors",
    "best-mini-greenhouse-for-hardening-off-seedlings",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
  ],
  "why-seedlings-get-leggy": [
    "how-to-prevent-damping-off-in-seedlings",
    "do-you-need-a-fan-for-seedlings",
    "best-fan-for-seedlings-indoors",
    "best-watering-method-for-seedlings-indoors",
  ],

  // Season Extension & Plant Protection
  "best-clips-and-hoops-for-securing-frost-cloth": [
    "how-to-add-2-to-4-weeks-to-your-growing-season",
    "floating-row-cover-vs-frost-blanket",
    "cold-frame-vs-low-tunnel",
    "how-many-degrees-does-frost-cloth-protect",
  ],
  "best-clips-for-holding-shade-cloth-in-wind": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-shade-cloth-setup-for-west-facing-gardens",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
    "best-greenhouse-repair-tape-for-torn-plastic",
  ],
  "best-cold-frame-for-raised-beds": [
    "cold-frame-vs-low-tunnel",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
    "best-mini-greenhouse-for-starting-seedlings-outdoors",
    "best-mini-greenhouse-shelf-for-balcony-gardens",
  ],
  "best-frost-blanket-for-tomatoes": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "best-frost-cloth-for-vegetable-gardens-by-temperature-rating": [
    "how-to-add-2-to-4-weeks-to-your-growing-season",
    "floating-row-cover-vs-frost-blanket",
    "cold-frame-vs-low-tunnel",
    "how-many-degrees-does-frost-cloth-protect",
  ],
  "best-greenhouse-repair-tape-for-torn-plastic": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-shade-cloth-setup-for-west-facing-gardens",
    "best-clips-for-holding-shade-cloth-in-wind",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
  ],
  "best-greenhouse-tomato-support-system-for-home-gardeners": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-shade-cloth-setup-for-west-facing-gardens",
    "best-clips-for-holding-shade-cloth-in-wind",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
  ],
  "best-insect-netting-for-brassicas": [
    "insect-netting-vs-row-cover-for-brassicas",
    "best-insect-netting-height-for-raised-bed-tunnels",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "best-insect-netting-height-for-raised-bed-tunnels": [
    "insect-netting-vs-row-cover-for-brassicas",
    "best-insect-netting-for-brassicas",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "best-low-tunnel-kit-for-home-vegetable-gardens": [
    "best-cold-frame-for-raised-beds",
    "cold-frame-vs-low-tunnel",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
    "best-mini-greenhouse-for-starting-seedlings-outdoors",
  ],
  "best-low-tunnel-setup-for-wind-protection-vs-insect-control": [
    "insect-netting-vs-row-cover-for-brassicas",
    "best-insect-netting-for-brassicas",
    "best-insect-netting-height-for-raised-bed-tunnels",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "best-mini-greenhouse-shelf-for-balcony-gardens": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-shade-cloth-setup-for-west-facing-gardens",
    "best-clips-for-holding-shade-cloth-in-wind",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
  ],
  "best-netting-for-carrot-rust-fly-vs-cabbage-moth": [
    "insect-netting-vs-row-cover-for-brassicas",
    "best-insect-netting-for-brassicas",
    "best-insect-netting-height-for-raised-bed-tunnels",
  ],
  "best-place-to-buy-season-extension-supplies-for-home-gardeners": [
    "how-to-add-2-to-4-weeks-to-your-growing-season",
    "floating-row-cover-vs-frost-blanket",
    "cold-frame-vs-low-tunnel",
    "how-many-degrees-does-frost-cloth-protect",
  ],
  "best-repair-kit-for-mini-greenhouse-covers": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-shade-cloth-setup-for-west-facing-gardens",
    "best-clips-for-holding-shade-cloth-in-wind",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
  ],
  "best-row-cover-for-early-spring-brassicas": [
    "insect-netting-vs-row-cover-for-brassicas",
    "best-insect-netting-for-brassicas",
    "best-insect-netting-height-for-raised-bed-tunnels",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "best-row-cover-hoops-for-raised-beds": [
    "how-to-add-2-to-4-weeks-to-your-growing-season",
    "floating-row-cover-vs-frost-blanket",
    "cold-frame-vs-low-tunnel",
    "how-many-degrees-does-frost-cloth-protect",
  ],
  "best-setup-for-extending-pepper-harvest-into-fall": [
    "is-it-too-late-to-plant-peppers",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "how-cold-is-too-cold-for-pepper-seedlings",
    "what-temperature-is-safe-to-transplant-peppers",
  ],
  "best-shade-cloth-percentage-for-tomatoes-vs-lettuce": [
    "best-shade-cloth-setup-for-west-facing-gardens",
    "best-clips-for-holding-shade-cloth-in-wind",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
    "best-greenhouse-repair-tape-for-torn-plastic",
  ],
  "best-shade-cloth-setup-for-west-facing-gardens": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-clips-for-holding-shade-cloth-in-wind",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
    "best-greenhouse-repair-tape-for-torn-plastic",
  ],
  "best-way-to-secure-row-cover-in-high-wind": [
    "how-to-add-2-to-4-weeks-to-your-growing-season",
    "floating-row-cover-vs-frost-blanket",
    "cold-frame-vs-low-tunnel",
    "how-many-degrees-does-frost-cloth-protect",
  ],
  "best-zipper-door-kit-for-diy-greenhouse-plastic": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-shade-cloth-setup-for-west-facing-gardens",
    "best-clips-for-holding-shade-cloth-in-wind",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
  ],
  "cold-frame-vs-low-tunnel": [
    "best-cold-frame-for-raised-beds",
    "cold-frame-vs-mini-greenhouse-for-seedlings",
    "best-mini-greenhouse-for-starting-seedlings-outdoors",
    "best-mini-greenhouse-shelf-for-balcony-gardens",
  ],
  "floating-row-cover-vs-frost-blanket": [
    "how-to-add-2-to-4-weeks-to-your-growing-season",
    "cold-frame-vs-low-tunnel",
    "how-many-degrees-does-frost-cloth-protect",
    "best-frost-cloth-for-vegetable-gardens-by-temperature-rating",
  ],
  "greenhouse-patch-tape-vs-clear-tarp-tape": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-shade-cloth-setup-for-west-facing-gardens",
    "best-clips-for-holding-shade-cloth-in-wind",
    "shade-cloth-clips-vs-bungee-cords-for-raised-beds",
  ],
  "how-many-degrees-does-frost-cloth-protect": [
    "how-to-add-2-to-4-weeks-to-your-growing-season",
    "floating-row-cover-vs-frost-blanket",
    "cold-frame-vs-low-tunnel",
    "best-frost-cloth-for-vegetable-gardens-by-temperature-rating",
  ],
  "how-to-add-2-to-4-weeks-to-your-growing-season": [
    "floating-row-cover-vs-frost-blanket",
    "how-many-degrees-does-frost-cloth-protect",
    "cold-frame-vs-low-tunnel",
    "best-row-cover-hoops-for-raised-beds",
  ],
  "insect-netting-vs-row-cover-for-brassicas": [
    "best-insect-netting-for-brassicas",
    "best-insect-netting-height-for-raised-bed-tunnels",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "metal-vs-fiberglass-garden-hoops-for-row-cover": [
    "how-to-add-2-to-4-weeks-to-your-growing-season",
    "floating-row-cover-vs-frost-blanket",
    "cold-frame-vs-low-tunnel",
    "how-many-degrees-does-frost-cloth-protect",
  ],
  "pop-up-plant-protector-vs-insect-net-tunnel": [
    "insect-netting-vs-row-cover-for-brassicas",
    "best-insect-netting-for-brassicas",
    "best-insect-netting-height-for-raised-bed-tunnels",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "shade-cloth-clips-vs-bungee-cords-for-raised-beds": [
    "best-shade-cloth-percentage-for-tomatoes-vs-lettuce",
    "best-shade-cloth-setup-for-west-facing-gardens",
    "best-clips-for-holding-shade-cloth-in-wind",
    "best-greenhouse-repair-tape-for-torn-plastic",
  ],

  // Crop-Specific Timing Questions
  "best-reusable-vine-clips-for-peppers-and-eggplant": [
    "is-it-too-late-to-plant-peppers",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "how-cold-is-too-cold-for-pepper-seedlings",
    "what-temperature-is-safe-to-transplant-peppers",
  ],
  "best-seed-starting-kit-for-tomatoes-and-peppers": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "best-seed-starting-trays": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "can-tomato-seedlings-survive-a-light-frost": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "how-cold-is-too-cold-for-pepper-seedlings": [
    "is-it-too-late-to-plant-peppers",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "what-temperature-is-safe-to-transplant-peppers",
    "best-setup-for-extending-pepper-harvest-into-fall",
  ],
  "how-cold-is-too-cold-for-tomato-seedlings": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "best-products-to-ripen-tomatoes-before-frost",
  ],
  "is-45-degrees-too-cold-for-tomato-plants": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "is-it-too-late-to-plant-beans": [
    "when-is-it-too-late-to-plant-for-fall-harvest",
    "is-it-too-late-to-plant-cucumbers",
    "is-it-too-late-to-plant-pumpkins",
    "is-it-too-late-to-plant-tomatoes",
  ],
  "is-it-too-late-to-plant-cucumbers": [
    "when-is-it-too-late-to-plant-for-fall-harvest",
    "is-it-too-late-to-plant-beans",
    "is-it-too-late-to-plant-pumpkins",
    "is-it-too-late-to-plant-tomatoes",
  ],
  "is-it-too-late-to-plant-peppers": [
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "how-cold-is-too-cold-for-pepper-seedlings",
    "what-temperature-is-safe-to-transplant-peppers",
    "best-setup-for-extending-pepper-harvest-into-fall",
  ],
  "is-it-too-late-to-plant-pumpkins": [
    "when-is-it-too-late-to-plant-for-fall-harvest",
    "is-it-too-late-to-plant-beans",
    "is-it-too-late-to-plant-cucumbers",
    "is-it-too-late-to-plant-tomatoes",
  ],
  "is-it-too-late-to-plant-tomatoes": [
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
    "best-products-to-ripen-tomatoes-before-frost",
  ],
  "too-late-to-plant-peppers": [
    "is-it-too-late-to-plant-peppers",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "how-cold-is-too-cold-for-pepper-seedlings",
    "what-temperature-is-safe-to-transplant-peppers",
  ],
  "too-late-to-start-peppers-in-zone-4": [
    "is-it-too-late-to-plant-peppers",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "how-cold-is-too-cold-for-pepper-seedlings",
    "what-temperature-is-safe-to-transplant-peppers",
  ],
  "too-late-to-start-tomatoes-in-zone-4": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "too-late-to-start-tomatoes-in-zone-5": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "what-temperature-is-safe-to-transplant-peppers": [
    "is-it-too-late-to-plant-peppers",
    "will-peppers-mature-before-first-frost-in-a-short-season",
    "how-cold-is-too-cold-for-pepper-seedlings",
    "best-setup-for-extending-pepper-harvest-into-fall",
  ],
  "when-to-start-tomatoes-in-zone-3": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "will-tomatoes-grow-in-a-100-day-growing-season": [
    "is-it-too-late-to-plant-tomatoes",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
    "best-products-to-ripen-tomatoes-before-frost",
  ],

  // Seeds, Varieties & Garden Gifts
  "best-garden-planner-gift-certificate": [
    "best-gift-for-someone-starting-a-vegetable-garden",
    "best-gift-for-a-vegetable-gardener-who-has-everything",
    "best-gift-seed-collection-for-gardeners",
  ],
  "best-garden-planner-subscription-gift-for-gardeners": [
    "best-gift-for-someone-starting-a-vegetable-garden",
    "best-gift-for-a-vegetable-gardener-who-has-everything",
    "best-gift-seed-collection-for-gardeners",
  ],
  "best-gardening-software-gift-for-beginners": [
    "best-gift-for-someone-starting-a-vegetable-garden",
    "best-gift-for-a-vegetable-gardener-who-has-everything",
    "best-gift-seed-collection-for-gardeners",
  ],
  "best-gift-for-a-vegetable-gardener-who-has-everything": [
    "best-gift-for-someone-starting-a-vegetable-garden",
    "best-gift-seed-collection-for-gardeners",
    "best-seed-company-gift-card-for-gardeners",
  ],
  "best-gift-for-someone-starting-a-vegetable-garden": [
    "best-gift-for-a-vegetable-gardener-who-has-everything",
    "best-gift-seed-collection-for-gardeners",
    "best-seed-company-gift-card-for-gardeners",
  ],
  "best-gift-seed-collection-for-gardeners": [
    "best-gift-for-someone-starting-a-vegetable-garden",
    "best-gift-for-a-vegetable-gardener-who-has-everything",
    "best-seed-company-gift-card-for-gardeners",
  ],
  "best-pollination-bags-for-pepper-seed-saving": [
    "best-seed-storage-box-for-vegetable-seeds",
    "best-seed-organizer-binder-for-gardeners",
    "binder-vs-box-for-storing-seed-packets",
    "best-seed-saving-envelopes-for-home-gardeners",
  ],
  "best-pollination-bags-for-saving-tomato-or-pepper-seed": [
    "best-seed-storage-box-for-vegetable-seeds",
    "best-seed-organizer-binder-for-gardeners",
    "binder-vs-box-for-storing-seed-packets",
    "best-seed-saving-envelopes-for-home-gardeners",
  ],
  "best-retailer-for-fast-maturing-vegetable-varieties": [
    "best-seed-company-for-short-season-gardens",
    "best-seed-company-for-fast-maturing-varieties",
    "best-seed-company-for-cool-climate-vegetables",
    "best-seed-company-for-succession-planting",
  ],
  "best-seed-collection-for-beginner-vegetable-gardeners": [
    "best-seed-company-for-short-season-gardens",
    "best-seed-company-for-fast-maturing-varieties",
    "best-retailer-for-fast-maturing-vegetable-varieties",
    "best-seed-company-for-cool-climate-vegetables",
  ],
  "best-seed-company-for-container-vegetables-in-cool-climates": [
    "best-seed-company-for-short-season-gardens",
    "best-seed-company-for-fast-maturing-varieties",
    "best-retailer-for-fast-maturing-vegetable-varieties",
    "best-seed-company-for-cool-climate-vegetables",
  ],
  "best-seed-company-for-cool-climate-vegetables": [
    "best-seed-company-for-short-season-gardens",
    "best-seed-company-for-fast-maturing-varieties",
    "best-retailer-for-fast-maturing-vegetable-varieties",
    "best-seed-company-for-succession-planting",
  ],
  "best-seed-company-for-fast-maturing-varieties": [
    "best-seed-company-for-short-season-gardens",
    "best-retailer-for-fast-maturing-vegetable-varieties",
    "best-seed-company-for-cool-climate-vegetables",
    "best-seed-company-for-succession-planting",
  ],
  "best-seed-company-for-short-season-gardens": [
    "best-seed-company-for-fast-maturing-varieties",
    "best-retailer-for-fast-maturing-vegetable-varieties",
    "best-seed-company-for-cool-climate-vegetables",
    "best-seed-company-for-succession-planting",
  ],
  "best-seed-company-for-succession-planting": [
    "best-seed-company-for-short-season-gardens",
    "best-seed-company-for-fast-maturing-varieties",
    "best-retailer-for-fast-maturing-vegetable-varieties",
    "best-seed-company-for-cool-climate-vegetables",
  ],
  "best-seed-company-gift-card-for-gardeners": [
    "best-gift-for-someone-starting-a-vegetable-garden",
    "best-gift-for-a-vegetable-gardener-who-has-everything",
    "best-gift-seed-collection-for-gardeners",
  ],
  "best-seed-organizer-binder-for-gardeners": [
    "best-seed-storage-box-for-vegetable-seeds",
    "binder-vs-box-for-storing-seed-packets",
    "best-seed-saving-envelopes-for-home-gardeners",
    "best-pollination-bags-for-pepper-seed-saving",
  ],
  "best-seed-saving-envelopes-for-home-gardeners": [
    "best-seed-storage-box-for-vegetable-seeds",
    "best-seed-organizer-binder-for-gardeners",
    "binder-vs-box-for-storing-seed-packets",
    "best-pollination-bags-for-pepper-seed-saving",
  ],
  "best-seed-storage-box-for-vegetable-seeds": [
    "best-seed-organizer-binder-for-gardeners",
    "binder-vs-box-for-storing-seed-packets",
    "best-seed-saving-envelopes-for-home-gardeners",
    "best-pollination-bags-for-pepper-seed-saving",
  ],
  "best-source-for-succession-planting-seed-mixes": [
    "best-seed-company-for-short-season-gardens",
    "best-seed-company-for-fast-maturing-varieties",
    "best-retailer-for-fast-maturing-vegetable-varieties",
    "best-seed-company-for-cool-climate-vegetables",
  ],
  "best-vegetable-seed-gift-box-for-gardeners": [
    "best-gift-for-someone-starting-a-vegetable-garden",
    "best-gift-for-a-vegetable-gardener-who-has-everything",
    "best-gift-seed-collection-for-gardeners",
  ],
  "pollination-bags-vs-organza-bags-for-seed-saving": [
    "best-seed-storage-box-for-vegetable-seeds",
    "best-seed-organizer-binder-for-gardeners",
    "binder-vs-box-for-storing-seed-packets",
    "best-seed-saving-envelopes-for-home-gardeners",
  ],

  // Supports, Grafting & Vertical Growing
  "best-cucumber-clips-for-vertical-growing": [
    "cucumber-clips-vs-tomato-clips",
    "best-hanging-line-clips-for-vine-crops",
    "best-trellis-connectors-for-cucumber-teepees",
    "diy-cucumber-trellis-connectors-vs-zip-ties",
  ],
  "best-hanging-line-clips-for-vine-crops": [
    "best-cucumber-clips-for-vertical-growing",
    "cucumber-clips-vs-tomato-clips",
    "best-trellis-connectors-for-cucumber-teepees",
    "diy-cucumber-trellis-connectors-vs-zip-ties",
  ],
  "best-trellis-connectors-for-cucumber-teepees": [
    "best-cucumber-clips-for-vertical-growing",
    "cucumber-clips-vs-tomato-clips",
    "best-hanging-line-clips-for-vine-crops",
    "diy-cucumber-trellis-connectors-vs-zip-ties",
  ],
  "best-watermelon-support-net-for-vertical-growing": [
    "best-cucumber-clips-for-vertical-growing",
    "cucumber-clips-vs-tomato-clips",
    "best-hanging-line-clips-for-vine-crops",
    "best-trellis-connectors-for-cucumber-teepees",
  ],
  "cucumber-clips-vs-tomato-clips": [
    "best-cucumber-clips-for-vertical-growing",
    "best-hanging-line-clips-for-vine-crops",
    "best-trellis-connectors-for-cucumber-teepees",
    "diy-cucumber-trellis-connectors-vs-zip-ties",
  ],
  "diy-cucumber-trellis-connectors-vs-zip-ties": [
    "best-cucumber-clips-for-vertical-growing",
    "cucumber-clips-vs-tomato-clips",
    "best-hanging-line-clips-for-vine-crops",
    "best-trellis-connectors-for-cucumber-teepees",
  ],
  "fruit-sling-vs-net-bag-for-trellised-melons": [
    "best-cucumber-clips-for-vertical-growing",
    "cucumber-clips-vs-tomato-clips",
    "best-hanging-line-clips-for-vine-crops",
    "best-trellis-connectors-for-cucumber-teepees",
  ],
  "tomato-hooks-vs-clips-for-vertical-growing": [
  ],

  // Watering, Sensors & Pest Protection
  "best-copper-tape-for-slugs-in-raised-beds": [
    "copper-tape-vs-copper-mesh-for-snails",
    "best-snail-barrier-for-patio-planters",
    "best-insect-netting-for-brassicas",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "best-garden-sensor-for-vacation-watering-checks": [
    "best-olla-system-for-vacation-watering-outdoors",
    "best-terracotta-watering-pots-for-vacation-watering",
    "drip-irrigation-vs-olla-pots-for-tomatoes",
    "best-sensor-for-monitoring-garden-beds-remotely",
  ],
  "best-olla-system-for-vacation-watering-outdoors": [
    "best-terracotta-watering-pots-for-vacation-watering",
    "drip-irrigation-vs-olla-pots-for-tomatoes",
    "best-garden-sensor-for-vacation-watering-checks",
    "best-sensor-for-monitoring-garden-beds-remotely",
  ],
  "best-sensor-for-monitoring-garden-beds-remotely": [
    "best-olla-system-for-vacation-watering-outdoors",
    "best-terracotta-watering-pots-for-vacation-watering",
    "drip-irrigation-vs-olla-pots-for-tomatoes",
    "best-garden-sensor-for-vacation-watering-checks",
  ],
  "best-snail-barrier-for-patio-planters": [
    "best-copper-tape-for-slugs-in-raised-beds",
    "copper-tape-vs-copper-mesh-for-snails",
    "best-insect-netting-for-brassicas",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "best-terracotta-watering-pots-for-vacation-watering": [
    "best-olla-system-for-vacation-watering-outdoors",
    "drip-irrigation-vs-olla-pots-for-tomatoes",
    "best-garden-sensor-for-vacation-watering-checks",
    "best-sensor-for-monitoring-garden-beds-remotely",
  ],
  "best-zigbee-soil-moisture-sensor-for-outdoor-plants": [
    "best-olla-system-for-vacation-watering-outdoors",
    "best-terracotta-watering-pots-for-vacation-watering",
    "drip-irrigation-vs-olla-pots-for-tomatoes",
    "best-garden-sensor-for-vacation-watering-checks",
  ],
  "copper-tape-vs-copper-mesh-for-snails": [
    "best-copper-tape-for-slugs-in-raised-beds",
    "best-snail-barrier-for-patio-planters",
    "best-insect-netting-for-brassicas",
    "best-netting-for-carrot-rust-fly-vs-cabbage-moth",
  ],
  "drip-irrigation-vs-olla-pots-for-tomatoes": [
    "best-olla-system-for-vacation-watering-outdoors",
    "best-terracotta-watering-pots-for-vacation-watering",
    "best-garden-sensor-for-vacation-watering-checks",
    "best-sensor-for-monitoring-garden-beds-remotely",
  ],
  "smart-soil-sensor-vs-manual-moisture-meter-for-gardens": [
    "best-olla-system-for-vacation-watering-outdoors",
    "best-terracotta-watering-pots-for-vacation-watering",
    "drip-irrigation-vs-olla-pots-for-tomatoes",
    "best-garden-sensor-for-vacation-watering-checks",
  ],

  // Garden Planning Tools & Software
  "is-a-garden-planner-subscription-worth-it": [
    "is-growveg-worth-it-for-home-gardeners",
    "best-garden-planner-subscription-gift-for-gardeners",
    "best-gardening-software-gift-for-beginners",
    "best-garden-planner-gift-certificate",
  ],
  "is-growveg-worth-it-for-home-gardeners": [
    "is-a-garden-planner-subscription-worth-it",
    "best-garden-planner-subscription-gift-for-gardeners",
    "best-gardening-software-gift-for-beginners",
    "best-garden-planner-gift-certificate",
  ],

  // Planting Tools, Storage & Garden Gear
  "best-hand-seeder-for-carrots-and-lettuce": [
    "best-mini-seed-spreader-for-tiny-seeds",
    "seed-dibber-vs-pencil-for-planting-seeds",
    "best-seed-dibber-for-seed-starting-trays",
    "best-widger-and-dibber-set-for-seedlings",
  ],
  "best-mini-seed-spreader-for-tiny-seeds": [
    "best-hand-seeder-for-carrots-and-lettuce",
    "seed-dibber-vs-pencil-for-planting-seeds",
    "best-seed-dibber-for-seed-starting-trays",
    "best-widger-and-dibber-set-for-seedlings",
  ],
  "best-products-to-ripen-tomatoes-before-frost": [
    "is-it-too-late-to-plant-tomatoes",
    "will-tomatoes-grow-in-a-100-day-growing-season",
    "how-many-growing-degree-days-do-tomatoes-need",
    "how-cold-is-too-cold-for-tomato-seedlings",
  ],
  "best-soil-thermometer": [
    "soil-thermometer-vs-infrared-thermometer-for-planting-decisions",
    "how-microclimates-change-frost-dates",
    "how-to-find-your-last-frost-date",
  ],
  "binder-vs-box-for-storing-seed-packets": [
    "best-seed-storage-box-for-vegetable-seeds",
    "best-seed-organizer-binder-for-gardeners",
    "best-seed-saving-envelopes-for-home-gardeners",
    "best-pollination-bags-for-pepper-seed-saving",
  ],
  "soil-thermometer-vs-infrared-thermometer-for-planting-decisions": [
    "best-soil-thermometer",
    "how-microclimates-change-frost-dates",
    "how-to-find-your-last-frost-date",
  ],
};
